### ISSUE TITLE
Matplotlib legend location - plt.legend or ax.legend?

### ISSUE THREAD

**Issue by rmih** [learn-co-curriculum/dsc-more-practice-with-matplotlib#1]
In the markdown describing how the legend is located the text describes using 
ax.legend (loc = 1) as the commancd.  but in the cell the command is plt.legend, which actually words.  Maybe a typo ...(repeated 4 times) ?

**Comment by mas16** [comment]
Hi rmih! This has been fixed. Thanks for bringing it to our attention.
